name: Count Every 30 Minutes

permissions:
  contents: write

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  count-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0  

    - name: Load Counter and Increment
      id: setup-counter
      run: |
        # Create counter.txt if it doesn't exist
        if [ ! -f counter.txt ]; then
          echo "0" > counter.txt
        fi

        # Read and increment counter
        counter=$(cat counter.txt)
        counter=$((counter + 1))
        echo "Counter value incremented to: $counter"

        # Save new counter
        echo "$counter" > counter.txt
        echo "counter=$counter" >> $GITHUB_OUTPUT

    - name: Commit and Push Changes
      run: |
        # Configure Git identity
        git config --global user.name "crc137"
        git config --global user.email "admin@coonlink.com"

        git add counter.txt
        git commit -m "Updated counter to ${{ steps.setup-counter.outputs.counter }}" || echo "No changes to commit"

        # Sync with remote before pushing
        git pull --rebase origin main || true
        git push || echo "Push failed (possibly due to concurrent updates)"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
