name: Counter Robot

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: Log level
        required: true
        default: warning
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  count-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load Counter and Increment
        id: setup-counter
        run: |
          COUNTER_FILE="counter.txt"

          if [ ! -f "$COUNTER_FILE" ]; then
            echo "0" > "$COUNTER_FILE"
          fi

          counter=$(cat "$COUNTER_FILE")
          counter=$((counter + 1))
          echo "$counter" > "$COUNTER_FILE"
          echo "Counter incremented to $counter"
          echo "counter=$counter" >> "$GITHUB_OUTPUT"

      - name: Commit and Push Changes
        run: |
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_NAME }}"

          if git diff --quiet; then
            echo "No changes to commit."
          else
            git add counter.txt
            git commit -m "🤖 Robot: Counter incremented to ${{ steps.setup-counter.outputs.counter }}"
            git push "https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git"
          fi
