name: Count Every 30 Minutes

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: Log level
        required: true
        default: warning
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  count-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Load Counter and Increment
      id: setup-counter
      run: |
        if [ ! -f counter.txt ]; then
          echo "0" > counter.txt
        fi

        # Read current counter
        counter=$(cat counter.txt)
        counter=$((counter + 1))
        echo "Counter value incremented to: $counter"
        echo "$counter" > counter.txt
        echo "counter=$counter" >> $GITHUB_OUTPUT

    - name: Commit and Push Changes
      run: |
        # Configure Git identity
        git config --global user.name "crc137"
        git config --global user.email "admin@coonlink.com"
        git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
        git add counter.txt
        git commit -m "Updated counter to ${{ steps.setup-counter.outputs.counter }}" || echo "No changes to commit"
        git push
